services:
  interior_gen:
    container_name: interior_gen
    build: .
    image: interior_gen:latest
    env_file: .env
    ports: 
      - 6000:6000
    environment:
      - HOST=0.0.0.0
      - PORT=6000
    volumes:
      - ./jobs:/app/jobs
    restart: no
